### PR TITLE
settings.AUTH_USER_MODEL

### PR DESCRIPTION
**Pull request by bashu**

### CODE REVIEW

**Comment by extremewaysback** [comment]
follow the updates of DaryAntony, I finally installed the django-tracking by fixing the error:
django.core.exceptions.ImproperlyConfigured: Requested setting CACHES, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

**Comment by extremewaysback** [comment]
Dear Bashu,

Thank you very much for your help.
I got the problem fixed according to your tips.
Thanks again!

**Comment by bashu** [comment]
O hai, Origin!

Well... you're welcome. I did not even answered on your first message...

Anyway I going to update this app to be sure it works with django 1.8+ and python 3

New version will be released on this weekend, thank for your interest!

**Comment by extremewaysback** [comment]
Haha, Your tip gave me the right direction ~.~! Looking forward to your new version!

**Pull request merged**
